name: test

on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - editors
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - editors

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version:
          - 'stable'
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
#       - run: sudo apt-get -y install libsass-dev
      - run: "npm install node-gyp -g"
      - run: "npm install cmake-js -g"
      - run: "choosenim show path -y"
      - run: nimble install -Y
      - run: nimble test
      - run: denim build src/${{ github.event.repository.name }}.nim --release --yes --cmake
